# Generated by Django 4.2.4 on 2023-10-27 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='rank',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
