# Generated by Django 4.2.4 on 2023-11-05 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0002_project_is_featured_project_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_link',
            field=models.URLField(default='f'),
            preserve_default=False,
        ),
    ]
